<?php

function reg_form_menu() {
  $items = array();
  $items['regform'] = array(
    'title' => '2015 Symposium Registration',
    'page callback' => 'reg_form_registration_page',
    'access arguments' => array('access content'),
    'file' => 'reg_form.registration.inc',
    'weight' => 1,
  );

  //$items['form_fun/tree'] = array(
  //  'title' => "I'm lost!",
  //  'page callback' => 'drupal_get_form',
  //  'page arguments' => array('form_fun_tree'),
  //  'access arguments' => array('access content'),
  //  'file' => 'form_fun.tree.inc',
  //  'weight' => 3,
  //);
  //
  //$items['form_fun/states'] = array(
  //  'title' => "Partners!",
  //  'page callback' => 'drupal_get_form',
  //  'page arguments' => array('form_fun_states_form'),
  //  'access arguments' => array('access content'),
  //  'file' => 'form_fun.states.inc',
  //  'weight' => 4,
  //);

  return $items;
}
