<?php
 
/*
 * @file
 * General module file for IDMOD
 */

 

/**
 * Implementation of hook_field_display_alter
 */
function idmod_field_display_node_alter(&$display, $context) {
  // Leave field labels out of the search index.
  if($context['entity']->type == 'publications') {
    // Look for our entity type
    
    if (isset($context['entity']->field_publications_author['und'][0]['entity']->label)) {
      // Loop through the author array
      // TODO: Each label is process at least three times... could set a flag and stop that BS
      foreach ($context['entity']->field_publications_author['und'] as $key => $item) {
        $label = $item['entity']->field_profile_first_name['und'][0]['value'];
        $label .= ' ';
        $label .= $item['entity']->field_profile_last_name['und'][0]['value'];
        $context['entity']->field_publications_author['und'][$key]['entity']->label =  $label;
      }
    } 
  }

}

/**
 * Implements hook_context_load_alter().
 * http://drupalcontrib.org/api/drupal/contributions%21context%21context.api.php/function/hook_context_load_alter/7
 */
function idmod_context_load_alter(&$context) {
  // We need to make sure that the context menu blocks are ordered correctly via context.
  // Start with the search form and make it the "lightest". 
  
  $debug = $context;
  if ($context->name == 'all_pages') {
    $context->reactions['block']['blocks']['search-form']['weight'] = -20;
  }
  if ($context->name == 'publications_page') {
    $context->reactions['block']['blocks']['block-5']['weight'] = -10;
  }
}









