<?php
 
/*
 * @file
 * General module file for IDMOD
 */

 

/**
 *  Implementation of hook_menu
 */
function idmod_menu() {
  $items = array();
  $items['publications'] = array(
    'title' => 'Publications',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idmod_publications_author', 2),
    'access arguments' => array('access content'),
    'file' => 'idmod.publications.inc',
    //'weight' => 1,
  );
  
  $items['publications/%'] = array(
    'title' => 'Publications',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('idmod_publications_author', 2),
    'access arguments' => array('access content'),
    'file' => 'idmod.publications.inc',
    //'weight' => 1,
  );  
  
  return $items;
}


function idmod_publications_page() {
  return drupal_get_form('idmod_publications_author');
}


/**
 * Implementation of hook_field_display_alter
 * Convert the reference to profile entity "Main profile" to actual name. 
 */
function idmod_field_display_node_alter(&$display, $context) {
  
  switch ($context['entity']->type) {
    case 'publications':
      if (isset($context['entity']->field_publications_author['und'][0]['entity']->label)) {
        // Loop through the author array
        // TODO: Each label is process at least three times... could set a flag and stop that BS
        foreach ($context['entity']->field_publications_author['und'] as $key => $item) {
          $label = $item['entity']->field_profile_first_name['und'][0]['value'];
          $label .= ' ';
          $label .= $item['entity']->field_profile_last_name['und'][0]['value'];
          $context['entity']->field_publications_author['und'][$key]['entity']->label =  $label;
        }
      }
      break;
      
    case 'polio_reports':
      if (isset($context['entity']->field_polo_report_author['und'][0]['entity']->label)) {
        foreach ($context['entity']->field_polo_report_author['und'] as $key => $item) {
          $label = $item['entity']->field_profile_first_name['und'][0]['value'];
          $label .= ' ';
          $label .= $item['entity']->field_profile_last_name['und'][0]['value'];
          $context['entity']->field_polo_report_author['und'][$key]['entity']->label =  $label;
        }        
      }
      
      break; 
  }

}


/**
 * Implements hook_context_load_alter().
 * http://drupalcontrib.org/api/drupal/contributions%21context%21context.api.php/function/hook_context_load_alter/7
 */
function idmod_context_load_alter(&$context) {
  // We need to make sure that the context menu blocks are ordered correctly via context.
  // Start with the search form and make it the "lightest". 
  
  if ($context->name == 'all_pages') {
    $context->reactions['block']['blocks']['search-form']['weight'] = -20;
  }
  if ($context->name == 'publications_page') {
    $context->reactions['block']['blocks']['block-5']['weight'] = -10;
  }
}



/**
 * Implementation of hook_entity_info_alter(&$entity_info).
 * Modify URL of taxonomy terms
 * Ref: http://drupal.stackexchange.com/questions/18784/how-to-modify-taxonomy-term-path-in-the-page-render-array
 * Ref: http://www.erikwebb.net/blog/changing-url-all-taxonomy-terms/
 
 * TODO:  9/13/2014- Why are we doing this? Prior to using DS?
 */
function idmod_entity_info_alter(&$entity_info) {

  $entity_info['taxonomy_term']['uri callback'] = 'idmod_taxonomy_term_uri';
  
  $entity_info['node']['view modes']['full_node'] = array(
    'label' => t('Full Node display'),
    'custom settings' => TRUE,
  );

}


function idmod_taxonomy_term_uri($term) {
  $new_url = NULL;
  
  switch ($term->name) {
      case "Applied Math":
          $new_url = 'research/math';
          break;
      case "Tuberculosis":
          $new_url = 'research/tuberculosis';
          break;
      case "HIV":
          $new_url = 'research/hiv';
          break;        
      case "Malaria":
        $new_url = 'research/malaria';
        break;
      case "Polio":
        $new_url = 'research/polio';
        break;
      case 'Epidemiology':
        $new_url = 'research/epidemiology';
        break;
  }  
  //return array('path' => 'research/numerical' . $term->tid);
  return array('path' => $new_url);
}

/**
 * Implementation of hook_entity_view_alter
 * We will modify the incoming data from the view handler before rendering.
 *
 * TODO: 2014-09-17: Check for foriegn author
 */

/* We can stick this into DS... or better yet, use DS API...
 */
function idmod_entity_view_alter(&$build, $type) {
  
  if($build['#bundle'] == 'publications') {
    $key = 0;
    // Set flag for foreign author
    $foreign_authors = $build['#node']->field_publication_foreign_author['und'][0]['value'];
    $foreign_authors_string = ($foreign_authors) ? t('IDM researchers included among the authors: ') : NULL;

      // Loop through authors listed
      while (isset($build['field_publications_author'][$key])) {
        // If there is more then one name, we add a comma to present item.
        if(isset($build['field_publications_author'][$key+1])) {
          // Now check to to see if role = Inactive. If so, we will take away link info...
          $author_uid = $build['field_publications_author']['#items'][$key]['entity']->uid;
          $author = user_load($author_uid);
          if (in_array ( 'Inactive', $author->roles )) {
            // This author is "inactive"
            $author_name_plain = $build['field_publications_author']['#object']->field_publications_author['und'][$key]['entity']->label;
            $build['field_publications_author'][$key]['#markup'] = $author_name_plain;
          }  
          $build['field_publications_author'][$key]['#markup'] .= ', ';
        }
        ++$key;
      }          
  }
}


/**
 * Implementation of hook_url_outbound_alter
 */
function idmod_url_outbound_alter(&$path, &$options, $original_path) {
  // We have altered the display of the user profile to our own internal view. 
  if (isset($options['entity_type'])) {
    if($options['entity_type'] == "profile2") {
      //intercept and modify the link
      $path = 'team/bio/' . $options['entity']->uid;
      $options['fragment'] = null;
    }
  }
}


/**
 * hook_entity_view($entity
 * Act on entities being assembled before rendering
 */
function idmod_entity_view($entity, $type, $view_mode, $langcode) {
  // CHeck "foreign author" field. If checked... don't display any author
  
  if (isset( $entity->field_publication_foreign_author['und'][0]['value'])) {
    if ($entity->field_publication_foreign_author['und'][0]['value']) {
      // Remove all authors
      //unset ($entity->content['field_publications_author']);
    }
  } 
}


/**
 * Perform setup task for non-cached pages
 * Purpose: To separate special use CSS and JS into unique files.
 * Reference: https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_add_js/7
 * Reference: Owl Carousel: http://smashingboxes.github.io/OwlCarousel2/index.html
 */
function idmod_init() {
  
  drupal_add_css(drupal_get_path('module', 'idmod') . '/slicknav/slicknav.css');
  drupal_add_js(drupal_get_path('module', 'idmod') . '/slicknav/jquery.slicknav.min.js', array(
  'scope' => 'footer',
  ));
  
  //drupal_add_js('http://amp.azure.net/libs/amp/1.7.1/azuremediaplayer.min.js', 'external');
  //drupal_add_css('http://amp.azure.net/libs/amp/1.7.1/skins/amp-default/azuremediaplayer.min.css', 'external');
  //

  
  //Setup for WOCO (used in footer)
  drupal_add_css(drupal_get_path('module', 'idmod') . '/woco/woco-accordion.css');
  drupal_add_js(drupal_get_path('module', 'idmod') . '/woco/woco.accordion.js');
  
  drupal_add_js(drupal_get_path('module', 'idmod') . '/js/fp.js', array(
  'scope' => 'footer',
  )); 
  
  
  //Load conditional CSS and JS
  $path = current_path();
  if (drupal_is_front_page()) {
    
    
    drupal_add_css(libraries_get_path('owlcarousel')  . '/assets/owl.carousel.min.css');
    drupal_add_css(libraries_get_path('owlcarousel')  . '/assets/owl.theme.default.css');
    
    drupal_add_js(drupal_get_path('module', 'idmod') . '/js/owl_carousel.js', array(
      'scope' => 'footer',
    ));
    
    drupal_add_js(libraries_get_path('owlcarousel')  . '/owl.carousel.min.js', array(
      'scope' => 'footer',
      
      
    ));
    
   
  }
  
  // Check to see if we should load Owl JS to currant page.
  // 2/14/2016: depends on owl carousel model for adding script tag to bottom of pages.
  //$path = currant_path();
  //NOTE: Remove for production. We won't be calling node/172 directly. 
  
  if ($path == 'node/172') {
 
    drupal_add_css(libraries_get_path('owlcarousel')  . '/assets/owl.carousel.min.css');
    drupal_add_css(libraries_get_path('owlcarousel')  . '/assets/owl.theme.default.css');
  
    drupal_add_js(drupal_get_path('module', 'idmod') . '/js/owl_carousel.js', array(
    'scope' => 'footer',
    ));
    drupal_add_js(libraries_get_path('owlcarousel')  . '/owl.carousel.min.js', array(
    'scope' => 'footer',
    ));    
  }
  
  
  //if ($path == 'node/10') {
  //  drupal_add_js(drupal_get_path('module', 'idmod') . '/js/fp.js');
  //}  
  //
  //
  //

 

}

